name: lof
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.9
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - gym
  - pip
  - pip:
      - gym[classic_control]
      - ipython
      - gymnasium==0.28.1
      - pandas
      - mujoco
      - imageio
      - moviepy
      - scikit-learn
